import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const VAULT_PLUGIN_DIR = "/home/lukas/Documents/ObsidianVaults/Sync/ChessBrain/.obsidian/plugins/chess-vault-manager";

const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(async () => {
			try {
				if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
					fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
				}

				await fs.promises.copyFile('main.js', path.join(VAULT_PLUGIN_DIR, 'main.js'));
				await fs.promises.copyFile('manifest.json', path.join(VAULT_PLUGIN_DIR, 'manifest.json'));
				if (fs.existsSync('styles.css')) {
					await fs.promises.copyFile('styles.css', path.join(VAULT_PLUGIN_DIR, 'styles.css'));
				}

				console.log(`[Updated] Copied files to ${VAULT_PLUGIN_DIR}`);
			} catch (e) {
				console.error("[Error] Failed to copy files to vault:", e);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
